@CrudProductsApi_HostAddress = http://localhost:5000

GET {{CrudProductsApi_HostAddress}}/
Accept: application/json

###

GET {{CrudProductsApi_HostAddress}}/health
Accept: application/json

###

GET {{CrudProductsApi_HostAddress}}/produtos
Accept: application/json

###

GET {{CrudProductsApi_HostAddress}}/produtos/1
Accept: application/json

###

GET {{CrudProductsApi_HostAddress}}/produtos/999
Accept: application/json

###

POST {{CrudProductsApi_HostAddress}}/produtos
Content-Type: application/json
Accept: application/json

{
  "nome": "Webcam Full HD",
  "preco": 199.90
}

###

POST {{CrudProductsApi_HostAddress}}/produtos
Content-Type: application/json
Accept: application/json

{
  "nome": "",
  "preco": 0
}

###

PUT {{CrudProductsApi_HostAddress}}/produtos/1
Content-Type: application/json
Accept: application/json

{
  "nome": "Mouse sem fio atualizado",
  "preco": 99.90
}

###

DELETE {{CrudProductsApi_HostAddress}}/produtos/1
Accept: application/json
